- name: Deploy to Production Server
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    passphrase: ${{ secrets.SSH_PASSPHRASE }}
    script_stop: true
    debug: true
    script: |
      cd /var/www/papierkrake
      git checkout main
      git pull origin main
      npm ci
      npm run build
      pm2 restart papierkrake-prod || pm2 start ecosystem.config.js --only papierkrake-prod
