name: Deploy PapierKrake to Development
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connectivity to server..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "echo Connection successful"
        
      - name: Deploy to Development Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          debug: true
          script: |
  echo "==== Starting deployment ===="
  whoami
  echo "==== Current directory ===="
  pwd
  echo "==== Changing to application directory ===="
  cd /var/www/papierkrake || echo "Directory does not exist"
  echo "==== Current git status ===="
  git status
  echo "==== Fetching from remote ===="
  git fetch origin
  echo "==== Available branches ===="
  git branch -a
  echo "==== Checking out branch ===="
  # Rest of the script...script: |
